import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { Any2 } from '../components/Any2'
// import { Button1 } from '../components/button'
// import { Button2 } from '../components/button/index1'
import { About } from '../components/html-containers/about'
import { AnyKindOfItSolutions } from '../components/html-containers/any-kind-of-it-solutions'
import { Costumer } from '../components/html-containers/custumer'
import { Footer } from '../components/html-containers/footer'
import { Footer2 } from '../components/html-containers/footer2'
import { Header } from '../components/html-containers/header'
import { HeaderBanner } from '../components/html-containers/header-banner'
import { HowWeCanHelp } from '../components/html-containers/how-we-can-help'
import { LatestNewsBlog } from '../components/html-containers/letest-news-blog'
import { OurPricingPlan } from '../components/html-containers/our-pricing-plan'
import { Poppular } from '../components/html-containers/poppular'
import Project from '../components/html-containers/project'
import { RecentProject } from '../components/html-containers/recent-project'
import { Review } from '../components/html-containers/review'

import { fetchAPI } from './api/fetchAPI'

async function fetchHomepage({ setHomepage }) {
  const fields = [
    '*',
    'first_screen.image1',
    'first_screen.image2',
    'how_we_can_help.services',
    'how_we_can_help.services.icon',
    'how_we_can_help.image1',
    'about',
    'about.image',
    'about.Feature',
    'Popular',
    'Popular.Popular', 
    'Popular.Popular.image'
  ]
  const homepage = await fetchAPI(
    {
      url: '/api/home-pages',
      params: {
        populate: fields.join(',')
      }
    }
  )
  if (typeof setHomepage === 'function') setHomepage(homepage.data[0].attributes)
  return homepage


}
const Home: NextPage = () => {
  const [homepage, setHomepage] = useState()

  useEffect(() => {
    fetchHomepage({ setHomepage })
  }, [])

  useEffect(() => {
    console.log('1111111homepage', homepage)


  }, [homepage])



  return (
    <div className="bg-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header ></Header>
      <HeaderBanner data={homepage?.first_screen}></HeaderBanner>
      <HowWeCanHelp data={homepage?.how_we_can_help}></HowWeCanHelp>
      <About data={homepage?.about}></About>
      <Poppular data={homepage?.Popular} ></Poppular>
      <Project></Project>
      <RecentProject></RecentProject>
      <Costumer></Costumer>
      <OurPricingPlan></OurPricingPlan>
      <Review></Review>
      <LatestNewsBlog></LatestNewsBlog>
      <AnyKindOfItSolutions></AnyKindOfItSolutions>
      <Footer></Footer>









    </div >




  )
}

export default Home
