import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { fetchAPI } from './api/fetchAPI'

const Home: NextPage = () => {
  const [potato, setPotato] = useState()
  const [lung, setLung] = useState()
  // useEffect(() => {
  //   const getPotato = async () => {
  //     const result = await fetchAPI({ url: '/api/tests' })
  //     setPotato(result.data[0].attributes)
  //     console.log('result.data[0].attributes', result.data[0].attributes)
  //   };
  //   const getLung = async () => {
  //     const result = await fetchAPI({ url: '/api/lungs' })
  //     setLung(result.data[0].attributes)
  //     console.log('result.data[0].attributes', result.data[0].attributes)
  //   };
  //   getPotato();
  //   getLung();
  // }, []);

  return (
    <div className="bg-red-500 text-3xl font-bold underline">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <p>title: {potato?.Title}</p>
      <p>Birthday: {potato?.Birthday}</p>
      <p>Hungry: {String(potato?.Hungry)}</p>

<p>name: {lung?.name}</p>
<p>height: {lung?.height}</p>
<p>description: {lung?.description}</p>
<p>email: {lung?.email}</p> */}
asdasdasd
    </div>
  )
}

export default Home
